echo 'version: 0.0
os: linux
files:
  - source: app/
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: root' > appspec.yml
