echo 'version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building project...
artifacts:
  files:
    - appspec.yml
    - scripts/*
    - app/**/*' > buildspec.yml
